### PR TITLE
allow deserializing launch.toml

### PR DESCRIPTION
**Pull request by hone**
I think we should make everything deserialize/serialize (some of these will be a bit non-trivial). I'm starting with `launch.toml` since I need it right now. :)

### CODE REVIEW

**Review by edmorley — APPROVED** [review]
Thank you :-)

**Comment by hone** [comment]
@edmorley do you usually wait for @Malax to chime in or should I just merge?

**Comment by edmorley** [comment]
It depends - your call! :-)

**Comment by Malax** [comment]
FWIW: I don't think I should be a blocker for PRs. :) I'm happy to review, but can't promise swift reviews right now.

**Pull request merged**
