### PR TITLE
example-02 fixes

### PR DESCRIPTION
**Pull request by dzuelke**
- bump buildpack API version
- move to vendored OpenSSL for easy cross-building from macOS
- add `Makefile.toml` and `package.toml` for easy builds
- fix `Gemfile.lock` checksumming (was looking in the wrong dir, always failing at runtime)

`layer_lifecycle_data` isn't working yet (none of the env vars end up in the built image), that somehow got broken in the 00e20e8ba5021923217b80d5d2fa4174d6f836b1 refactor

### CODE REVIEW

**Comment by Malax** [comment]
Hey David, thanks for the fixes!

I'm unsure if we want our Heroku build scripts in this repository. They make it much easier to get started with the examples but make them more opinionated. @hone, @schneems, @edmorley: Thoughts?

**Comment by edmorley** [comment]
I think we need to figure out the example story overall - at the moment we have many examples in varying states of out of date-ness:
- 2x `examples` in this repo that don't build / aren't tested in CI
- https://github.com/Malax/rust-cnb-starter
- https://github.com/heroku/heroku-buildpacks-repo-template

And then these implementations:
- https://github.com/heroku/buildpacks-jvm/tree/main/buildpacks/jvm-function-invoker
- https://github.com/heroku/procfile-cnb-rust

The difficulty is that:
1. We likely want both monorepo and single-buildpack examples (so having just a single example isn't viable)
2. We might not want Heroku/libherokubuildpack usages in this repo
3. Repos that aren't this repo (once tested in CI as changes are made), or an actual production buildpack repo are likely going to get out of date

One option would be to say that this repo is the only location for examples, and that those examples are solely single buildpacks not using `libherokubuildpack`, but that we also link out to actual production monorepo Heroku buildpacks in `examples/README.md`. And then we delete https://github.com/Malax/rust-cnb-starter and eventually https://github.com/heroku/heroku-buildpacks-repo-template (once we've stood up the per-lanuagage monorepos, that will then be where further changes evolve).

**Comment by schneems** [comment]
I feel like someone should be able to build a buildpack with just libcnb.rs. I think this is related to my prior comment of https://github.com/Malax/libcnb.rs/issues/92. 

If you agree then I think the next requirement is for someone to be able to build a buildpack correctly using our documentation. I would say a requirement of that documentation is it needs to stay in alignment with libcnb and to *that* end I would say it needs to at least be executed, ideally be tested, even more ideal would be to ensure that it works with pack. If it works with pack, then it needs to be able to compile to musl.

It's a bit of a give a mouse a cookie scenario. 

Some alternatives:

- We could make a "CNB on Rust book" similar to rustdoc book (and friends).
- We could have libcnb be ONLY the low level API and have another higher level lib that sits somewhere between libcnb and libherokubuildpack. (Not loving this, as I don't really know what would go in it).
- We could commit to a single, minimal example and then push other examples to another repo/library (like a book library). 
- We could have CI pull in one or more external example repos and build them.

Right now our own ecosystem is very fragmented. We've got random repos all over the place that may or may not be up-to-date and may or may not be maintained anymore.

Recap: We should have at least one working example in our repo. We should have at least one canonical/maintained example that actually compiles to the point where it can be run by pack (may or may not live in libcnb.rs). We should have automation that ensure these examples don't break via compilation/test.

**Comment by schneems** [comment]
I think i'm in favor of merging this in now and figuring out the next right thing later. We can always take out the makefile.toml at a future date. It's not serving anyone having broken examples in the repo right now.

**Review by schneems — APPROVED** [review]
We talked about this in planning today quickly. I want to merge this so the examples work. The larger question/problem/philosophy can be re-visited and talked about in the future. 

Ideally, these examples would have integration tests via cutlass or replacement. Ideally also the examples in the readme would be exercised as well https://github.com/Malax/libcnb.rs/issues/92. 

We need some forward progress and momentum. We can revisit this example and our example strategy in the future. I'm merging this in.

**Pull request merged**
